/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeInsertionSortLib */

#ifndef _Included_NativeInsertionSortLib
#define _Included_NativeInsertionSortLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeInsertionSortLib
 * Method:    insertion_sort
 * Signature: ([ID)V
 */
JNIEXPORT void JNICALL Java_NativeInsertionSortLib_insertion_1sort
  (JNIEnv *, jobject, jintArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
