/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeInsertionSortOperation */

#ifndef _Included_NativeInsertionSortOperation
#define _Included_NativeInsertionSortOperation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeInsertionSortOperation
 * Method:    insertionSort
 * Signature: ([ID)V
 */
JNIEXPORT void JNICALL Java_NativeInsertionSortOperation_insertionSort
  (JNIEnv *, jobject, jintArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
